### ISSUE TITLE
Eurotronic Spirit unoccupied/eco mode

### ISSUE THREAD

**Issue by tvv76** [Koenkk/zigbee-herdsman-converters#1249]
Eurotronic Spirit thermostat has 2 different temperature setpoints - occupied_heating_setpoint & unoccupied_heating_setpoint. Looks like these values shoud replace current_heating_setpoint instead of heating mode. But we have just 4 modes - auto, heat, boost, off. There is no Eco mode.
Who knows how to enable Eco Mode in this thermostat?

**Comment by allofmex** [comment]
What do you mean by "Eco mode"?

**Comment by tvv76** [comment]
> What do you mean by "Eco mode"?

Normal mode - current_heating_setpoint set to occupied_heating_setpoint.

Boost mode - current_heating_setpoint set to maximum. It's can be set by setting eurotronic_system_mode flag or by setting system_mode to 'boost'.

Windows opened mode (off) - current_setpoint set to 5 degrees C. Should the temperature fall suddenly, the window open detection mode is activated. The Spirit ZigBee
switches to the OFF mode for 15 minutes.
The window open mode is left automatically after 15 minutes and Spirit ZigBee restore its setpoint
temperature.

Eco mode - current_heating_setpoint set to unoccupied_heating_setpoint. I think device has method to turn this mode on, but I don't know how :-( Otherwise why it provide two different setpoints for occupied/unoccupied cases?

**Comment by allofmex** [comment]
Eurotronic does not have an eco-mode. Please have a look at Installation and [Operation Guide Spirit ZigBee](https://eurotronic.org/wp-content/uploads/2019/11/Spirit_ZigBee_BAL_web_EN_November-2019.pdf) at https://eurotronic.org/service/downloads/ (Chapter 6+).

You may see it the other way around:
`(un-)occupied` will set `current-setpoint`.

No matter if you write to `occupied` or `unoccupied`, it will always be copied to `current` setpoint. Additional: if you use device hardware button (or boost/window mode), it will also be reflected in `current`.
(un-)occupied setpoints are mandatory zigbee attributes, current_heating_setpoint is Eurotronic defined "internal" state, reflecting the setting, device is currently operating on.

The general hvacThermostat idea is (as far as I understood):

- We configure 2 temperatures (for "someone home" and "nobody home")
- some external device (coordinator/bridge/..) tells via `occupancy` attribute which of both is to be used at the moment.

It seems, Eurotrinic currently does not implement it. They had to implement `occupied` and `unoccupied` fields, because it is mandatory by Zigbee standard, but that's it. Let's hope for better firmware.

**Comment by tvv76** [comment]
I see. Thank you for explanations. I will try to use this knowleges.
