### ISSUE TITLE
Immax 4in1-Sensor-ZB3.0 not reporting occupancy

### ISSUE THREAD

**Issue by nextsux** [Koenkk/zigbee-herdsman-converters#1551]
Thanks for recent adding of Immax 4in1-Sensor-ZB3.0 which supports occupancy. Unfortunately occupancy is not reported and is still 0.

```
Zigbee2MQTT:debug 2020-09-13 19:40:26: Received Zigbee message from 'sensor_predsin', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-09-13 19:40:26: MQTT publish: topic 'zigbee2mqtt/sensor_predsin', payload '{"humidity":59.71,"illuminance":1,"illuminance_lux":0,"linkquality":60,"temperature":27.69}'
Zigbee2MQTT:debug 2020-09-13 19:42:47: Received Zigbee message from 'outlet_predsin', type 'read', cluster 'genTime', data '["time"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-09-13 19:43:05: Received Zigbee message from 'sensor_predsin', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":11761}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-09-13 19:43:05: MQTT publish: topic 'zigbee2mqtt/sensor_predsin', payload '{"humidity":59.71,"illuminance":11761,"illuminance_lux":14,"linkquality":55,"temperature":27.69}'
Zigbee2MQTT:debug 2020-09-13 19:43:21: Received Zigbee message from 'sensor_predsin', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":12042}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-09-13 19:43:21: MQTT publish: topic 'zigbee2mqtt/sensor_predsin', payload '{"humidity":59.71,"illuminance":12042,"illuminance_lux":15,"linkquality":57,"temperature":27.69}'
Zigbee2MQTT:debug 2020-09-13 19:44:08: Received Zigbee message from 'sensor_predsin', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":11761}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-09-13 19:44:08: MQTT publish: topic 'zigbee2mqtt/sensor_predsin', payload '{"humidity":59.71,"illuminance":11761,"illuminance_lux":14,"linkquality":55,"temperature":27.69}'
Zigbee2MQTT:debug 2020-09-13 19:44:18: Received Zigbee message from 'sensor_predsin', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":12042}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-09-13 19:44:18: MQTT publish: topic 'zigbee2mqtt/sensor_predsin', payload '{"humidity":59.71,"illuminance":12042,"illuminance_lux":15,"linkquality":57,"temperature":27.69}'
```

Have you make it work somehow @Nithador ?

**Comment by Nithador** [comment]
Hi @nextsux, occupancy works for me. I should receive several more units tomorrow, I will test them to see if any of them has the same issue.

**Comment by nextsux** [comment]
After two hours of playing it suddenly started to report it, I'm not pretty sure what I did - I think one of repairing did the job but I'm not convinced about sensors reliability

**Comment by Nithador** [comment]
So I just paired four more devices.
In my case the most difficult part was pairing itself. With two of them I had to reset the device at least 7 times to get the pairing done. It takes up to 4 minutes, so it is necessary to reset the device and wait for either successful pairing, or error message. In latter case, try again.
Then after successful pairing at first it does not report all the values. Again not sure why, but this is solved by itself after a minute or two.
In two cases the humidity was not reported even after some time, so I just took out the battery and put it back. That solved it and all of them works. Basically, every problem was solved by either reset, or turning off and on the battery.
When all gets settled the devices works without problem and none of the issues reappear, so that's good. It's just setup difficulties, which are not too big in my opinion.

One note though, I feel the motion detection sometimes takes some time, not sure if there are some computations in the background, but it surprised me. Maybe the sensitivity can be adjusted, not sure. 

If I'll have some spare time I will contact manufacturer about advanced setup and create manual for that, but no promises on that.

**Comment by nextsux** [comment]
I think this issue can be closed

**Comment by AlexKay88** [comment]
@Nithador and @nextsux 
Definition of Immax 07502L "4 in 1 multi sensor"
in [immax.ts](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/immax.ts)
is very similar to Fantem ZB003-X "4 in 1 multi sensor"
in [Fantem.ts](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/fantem.ts)
and already uses Fantem specific fromZigbee and toZigbee.

Differences are that Immax is missing `battery2` and `battery_voltage`
Is Immax 07502L operated with a single battery only while Fantem ZB003-X has 2 batteries inserted?

Illuminance calibration values for Immax look strange (+/- 10000) as if the values were related to illuminance_raw instead of lux.

Also some other value ranges are slightly different from Fantem.
When I created the converter for Fantem ZB003-X a couple of years ago I sniffed the Tuya SmartLife app with the respective values given from "original".

Could you please check if your Immax sensors operate fine after you added their fingerprints as white labels to fantem.ts?
