### ISSUE TITLE
Silvercrest HG06467: cannot select white spectrum color in HA

### ISSUE THREAD

**Issue by groenmarsmannetje** [Koenkk/zigbee-herdsman-converters#1816]
According to the box in which this Christmas tree light is packet it also supports white spectrum color range. But in HA I only get a RGB color picker, the slider with the white spectrum colors is not shown. 

Also when you change brightness the color changes to a white color. 

So it still needs some improvements, but very nice that it is already working.

**Comment by groenmarsmannetje** [comment]
The brightness issue seems related to what was mentioned here: 

https://github.com/Koenkk/zigbee-herdsman-converters/pull/1799#discussion_r530588329

**Comment by Ruftie** [comment]
same issue here

**Comment by MichielMag** [comment]
Hey all, just a heads up about this issue: this feature is indeed on the box of the lights, but for some reason you cannot control this in the Lidl Home app.

Since I've sniffed the traffic using the Lidl gateway + Android app, I couldn't find out how to control the spectrum.

I did send an e-mail to Lidl support asking if this will be added to the app later, but I've had no response yet.
