### ISSUE TITLE
lidle Silvercrest HG06467 led christmas fairy lights Zigbee Melinera smart LED string lights

### ISSUE THREAD

**Issue by elzershark** [Koenkk/zigbee-herdsman-converters#1848]
can you bring it this? Silvercrest HG06467

https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/HG06467.md#trigger-effects

would be great that is also possible to control the effects shown under "[Trigger effects](https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/HG06467.md#trigger-effects)"

https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L15386

**Comment by MichielMag** [comment]
Hey @elzershark,
Your comment is a bit unclear for me. Are you asking someone to support the Lidl christmas lights? Because that's already supported, but you may have to go on the dev branch.
https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

The effect's you're linking are literally for the LED christmas string, so I'm not sure what you're trying to say.

**Comment by elzershark** [comment]
Please look this:

https://github.com/ioBroker/ioBroker.zigbee/issues/874

**Comment by MichielMag** [comment]
That is another piece of software, can't help you with that. I see that someone commented that there's no expose and that is correct. It's a manufacturer-specific "effect". I did provide the JSON it expects in the docs you linked and that should be enough to help you.

**Comment by elzershark** [comment]
thx
