### ISSUE TITLE
Linkind ZS110040078 recognized as ZS1100400-IN-V1A0

### ISSUE THREAD

**Issue by stefangries** [Koenkk/zigbee-herdsman-converters#3003]
There are two Linkind Motion sensors. One is supported by Zigbee2MQTT (..A0), the other is not (..78). 

![image](https://user-images.githubusercontent.com/10342151/132388383-7c7b4b07-f6ac-4bb7-a938-88d5926de9b0.png)

Unfortunately, the ..78 is also recognised as ...A0. Therefore I cannot debug it as described in [the manual](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#1-pairing-the-device-with-zigbee2mqtt) to write a converter. How do I proceed here?

And by the way: No, unfortunately the ..78 does not work with the integrated converter of the ..A0. It pairs, but does not report any values.

**Comment by danieledwardgeorgehitchcock** [comment]
Are you getting warnings that the device isn't supported in Zigbee2MQTT, or is it that the device is being recognised as a different one?

Are there any differences between the two with respect to features?

It may just be that one is a white label / updated version of the other - In which case this should be the expected behaviour and will work fine in Zigbee2MQTT.

If you can post the entry for this device from your database.db, that might assist

**Comment by stefangries** [comment]
Since my device is now defective, this issue can be closed.
