### ISSUE TITLE
aiuto integrazione ledvance.js in zigbee2mqtt

### ISSUE THREAD

**Issue by davide5681** [Koenkk/zigbee-herdsman-converters#3040]
hi everyone, i didn't understand how to add the support of my ledvance zigbee2mqtt lamp. i read the guide but i can't understand, can someone help me? my lamp is a ledvance outdoor flex. in practice the outdoor rgb led strip. Thank you

**Comment by blackwiz4rd** [comment]
Hi,
isn't it already supported by zigbee2mqtt? https://github.com/Koenkk/zigbee-herdsman-converters/blob/ec363907a813a7b26bf144a52433bedb3d15f5c9/devices/ledvance.js

```
{
      zigbeeModel: ['Outdoor FLEX RGBW Z3'],
      model: '4058075208360',
      vendor: 'LEDVANCE',
      description: 'SMART+ outdoor flex multicolor',
      extend: extend.ledvance.light_onoff_brightness_colortemp_color({colorTempRange: [153, 526]}),
      ota: ota.ledvance,
  },
```

**Comment by davide5681** [comment]
yes but i didn't understand how i can add it to zigbee2mqtt.

**Comment by Rockman18** [comment]
Which version of the zigbee2mqtt plugin do you use ? The standard or the Edge version ?

The standard is updated once a month instead of the edge which is updated every day. The integration of your device was done on September 2nd, so perhaps you'll have to wait October to see this integration in the new version.

**Comment by blackwiz4rd** [comment]
> yes but i didn't understand how i can add it to zigbee2mqtt.

Have you installed Home Assistant or Domoticz as a user interface?
