### ISSUE TITLE
Get local_temperature from TV01-ZB without lights up display

### ISSUE THREAD

**Issue by JFox-sk** [Koenkk/zigbee-herdsman-converters#3416]
Hi,
I can get current local_temperature Tesla Smart Thermostat radiator valve [TV01-ZB](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/moes.js#L292) only using the workaround like described [here](https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html#local-temperature) (by setting local_temperature_calibration every time when I need to get current temperature). This solution is workable but on this device (TV01-ZB) it always lights up display when I set local_temperature_calibration. So it is not comfortable and it drains the battery. It would be useful to get local_temperature without lights-up the display. Original Tuya app can do it - the app shows the current temperature without lights-up the display of the device. 
I tried to read logs from hacked tuya Zigbee smart gateway when the Tuya app is getting the current temperature from the device, but I am not very wise about it. I can provide the logs if can it be useful for someone.

**Comment by vladi1234** [comment]
Use the online function.

**Comment by JFox-sk** [comment]
> Use the online function.
Hi @vladi1234 
thank you for your reply. Please, can you describe to me how can do it?
Thanks

**Comment by jakub-moravek** [comment]
Hi

@JFox-sk were you able to solve this problem? I am asking, because I am dealing with the same one. By the way, I figured out what @vladi1234 meant by online function. It is one of the attributes exposed by this device in Z2M, but it does not work. (Attached screenshot of part of my Z2M web interface)
![online_function](https://user-images.githubusercontent.com/77301088/203050030-7a9afb2c-45ad-4de6-a58f-76eddc866d3b.png)
My current approach is to create automation that sets  local_temperature_calibration + create some hinged cover that I put on the valve.
