### ISSUE TITLE
Eurotronic Spirit experiences

### ISSUE THREAD

**Issue by ReneHonig** [Koenkk/zigbee-herdsman-converters#383]
@mhelff , thanks for creating the Eurotronic Spirit device handler! #270 

Do you have any guidance/documentation on how to operate the device (.e.g. how to set various modes). Also, do you have any experience with the operating mode where you set the valve position directly? Do you know whether it possible to read the valve position when the device operates in 'normal' mode (i.e. where you specify a heating setpoint)?

Any sharing of your experiences with this device would be highly appreciated, as I am considering to use them for the whole house (just bought one for now for testing).

**Comment by mhelff** [comment]
No, i never used the manual mode. Actively reading the valve position should not be necessary because it is reported as soon as it changes (just remember the last pi_heating_demand, values 0-255)
All known modes and attributes are documented here: http://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html

My personal experience (4 devices):
Im using them only in automatic mode (set temperature through "current_heating_setpoint"). Window open/close are signaled through bit 4 and 5 of the attribute "eurotronic_system_mode". Translation from the window sensors (xiaomi) to the Spirit Zigbee is done by some simple logic in Node-Red.
That was more or less my only goal: To achieve a reliable window open detection and turn off the heater accordingly. When signalling window closed, the last current_heating_setpoint is automatically restored. All other values like the valve position i just collect for my statistics.

**Comment by ReneHonig** [comment]
Many thanks for your response and pointing me to the device specific info!

@Koenkk , is there a thermostat model in the homeasssitant.js setup, or does that need to be set-up first?

**Comment by Koenkk** [comment]
@ReneHonig no, there is no home assistant configuration for thermostats yet.
