### ISSUE TITLE
Question about Fan withModes and preset_modes

### ISSUE THREAD

**Issue by gizmocuz** [Koenkk/zigbee-herdsman-converters#6312]
I am struggling a bit with the Ikea STARKVIND air purifier model E2007
In the config object of MQTT i only receive

```
  "preset_modes": [
    "auto"
  ],
```

In Ikea.ts i noticed

`e.fan().withModes(['off', 'auto', '1', '2', '3', '4', '5', '6', '7', '8', '9']),`

And this is exactly what I would like to see here (tested sending this and working)

```
  "preset_modes": [
    "off",
    "auto",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ],
```

Nowhere in the config object I noticed "off,auto,1,2,3,4,5,6,7,8,9" so I wondered if there should be a relation between the two of them, or how we could extend the preset_modes here...

Hope someone could shine a light on this

Edit: In the web gui of Zigbee2MQTT there is a full dropdown with the above modes

**Comment by gizmocuz** [comment]
@Koenkk , Is it possible you can point me in a direction to make a PR for this?

**Comment by Koenkk** [comment]
> In the config object of MQTT i only receive

Which config object do you mean, the one received by HA?

**Comment by gizmocuz** [comment]
The config object received by the MQTT broker.

**Comment by daserra23** [comment]
Would be nice to see this working if possible.

**Comment by Koenkk** [comment]
> The config object received by the MQTT broker.
> 
> 

on which mqtt topic is it received?

**Comment by gizmocuz** [comment]
@Koenkk , in my case it is received here

homeassistant/fan/0x50325ffffeba55af/fan/config

and the payload of the config object is:

```
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state"
    }
  ],
  "command_topic": "zigbee2mqtt/AirPurifier/set/fan_state",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x50325ffffeba55af"
    ],
    "manufacturer": "IKEA",
    "model": "STARKVIND air purifier (E2007)",
    "name": "AirPurifier",
    "sw_version": "1.0.033"
  },
  "json_attributes_topic": "zigbee2mqtt/AirPurifier",
  "name": null,
  "object_id": "airpurifier",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.33.1-dev",
    "url": "https://www.zigbee2mqtt.io"
  },
  "percentage_command_template": "{{ {0:'off', 1:'1', 2:'2', 3:'3', 4:'4', 5:'5', 6:'6', 7:'7', 8:'8', 9:'9'}[value] | default('') }}",
  "percentage_command_topic": "zigbee2mqtt/AirPurifier/set/fan_mode",
  "percentage_state_topic": "zigbee2mqtt/AirPurifier",
  "percentage_value_template": "{{ {'off':0, '1':1, '2':2, '3':3, '4':4, '5':5, '6':6, '7':7, '8':8, '9':9}[value_json.fan_mode] | default('None') }}",
  "preset_mode_command_topic": "zigbee2mqtt/AirPurifier/set/fan_mode",
  "preset_mode_state_topic": "zigbee2mqtt/AirPurifier",
  "preset_mode_value_template": "{{ value_json.fan_mode if value_json.fan_mode in ['auto'] else 'None' | default('None') }}",
  "preset_modes": [
    "auto"
  ],
  "speed_range_max": 9,
  "speed_range_min": 1,
  "state_topic": "zigbee2mqtt/AirPurifier",
  "state_value_template": "{{ value_json.fan_state }}",
  "unique_id": "0x50325ffffeba55af_fan_zigbee2mqtt"
}
```

Above you can see there is only one preset mode (off) instead of all modes

  **"preset_modes": [
    "auto"
  ],**

**Comment by Koenkk** [comment]
These are included in the speeds, see the logic here: https://github.com/Koenkk/zigbee2mqtt/blob/ccc08a3fc76e49fedf562a3f14f71e362aed6d7c/lib/extension/homeassistant.ts#L512C6-L512C6

**Comment by gizmocuz** [comment]
I have looked at this, and also at the device Ikea.ts file
But I can't see what is to be modified so the **preset_modes**  are filled in correctly with all supported modes.
Or do you mean that MQTT users should take the value of **percentage_command_template** and translate this to **preset_modes** ?
In this case, is there a need for **preset_modes** ? As it is incomplete
I think it would make sense to support **preset_modes** and make (somewhere) a modification that it has all modes
As we also use this field for other hardware

**Comment by Koenkk** [comment]
Could you explain your use case a bit more?

**Comment by gizmocuz** [comment]
Sure, for example when using a climate device we have **preset_modes** and with this we create a gui element to easily switch between the different modes.
(same for a MQTT-AD select type)

Now we also want to put our fan in different modes, in the above fan example these modes are off, 1, 2, 3 etc... But I can imagine some fans have off, slow, medium, hard

But because with this fan (not sure if the problem persists with other fans as well), the only **preset_mode** it declares is "auto"

The device itself has 5 modes on the front

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/2265299/a0e068ab-a91e-4de3-bb37-7baedca18483)

Maybe internally it has more

But you would expect the preset_modes to be filled with the content of the first post above
It is also handled in Ikea.ts 

**e.fan().withModes(['off', 'auto', '1', '2', '3', '4', '5', '6', '7', '8', '9']),**

But where are these modes?

**Comment by Koenkk** [comment]
> with this we create a gui element to easily switch between the different modes.

Where do you create a GUI element? Where do you expect this modes to show up? The topic you showed is specific to Home Assistant, so I guess you want to set these modes from Home Assistant?

**Comment by gizmocuz** [comment]
No, I'm the author of Domoticz
The auto discovery topic is by default set to 'homeassistant' but end users could also fill in any other name

**Comment by gizmocuz** [comment]
For example a GUI element for a climate device that allows the user to select the different modes

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/2265299/e8cb201d-fc67-4e4d-8928-e0e861ae3f11)

**Comment by Koenkk** [comment]
I see now, for Home Assistant the z2m expose `preset_modes` are split over  `percentage_command` (`percentage_command_template`) and `preset_modes` in Home Assistant discovery payload. If I remember correctly, this is done to provide a nice user experience in Home Assistant (it will render a slider).

**Comment by gizmocuz** [comment]
Ok, but **preset_modes** only contain one value, indicating that you cannot switch between 'modes' as it only has one defined

If I look at the below (taken from Ikea.ts)

`e.fan().withModes(['off', 'auto', '1', '2', '3', '4', '5', '6', '7', '8', '9']),`

I would have expect a **preset_modes** field to be created and filled with all the above defined modes

The **percentage_command_template** only defines off (0) and 1 till 9, logical presentation is also Off, Auto, 1,2,3...

For a slider it could also use the fan_speed existence/range

I have no idea how it looks in HASS, but it seems to control it, they need a button for "auto" and a slider, looks to me a user has to double check if it's on auto or a slider value

But (i'm not sure) HASS is not using MQTT for ZWaveJS, would it be possible for a fan, when it declares 'withModes' to fill all modes in the **preset_modes** ?
If not, I will use both preset_modes and percentage_command_template, to create the selector element

**Comment by Koenkk** [comment]
The Z2M preset modes that are in speed are indeed not duplicated in HA preset modes

> But (i'm not sure) HASS is not using MQTT for ZWaveJS, would it be possible for a fan, when it declares 'withModes' to fill all modes in the preset_modes ?

@cmccambridge I know it's a long time ago, but since you changed this in https://github.com/Koenkk/zigbee2mqtt/pull/7359 , does you think it make sense to duplicate of the Z2M preset modes that are already mapped to the HA speed in HA preset modes? You have more experience with Home Assistant and fans than I do 😄

**Comment by cmccambridge** [comment]
Hi @Koenkk , @gizmocuz!

For Home Assistant in specific, no, I don't think that it would make sense to duplicate the "speed" modes into the Home Assistant `preset_modes` list. A Home Assistant fan entity (i.e. what HA expects to appear from MQTT discovery or any other Home Assistant integration) has _separate_ concepts of a `speed` versus a `preset mode`: https://developers.home-assistant.io/docs/core/entity/fan/

That page has the full details, but key quotes there:
- > The list of supported preset_modes. This is an arbitrary list of str and should not contain any speeds.
- > Preset modes should not include named (manual) speed settings as these should be represented as percentages.
    - This is why Z2M is mapping the ZCL `low`, `medium`, `high` to points on the speed slider instead
- > Manually setting a speed must disable any set preset mode. If it is possible to set a percentage speed manually without disabling the preset mode, create a switch or service to represent the mode.
    - This is an interesting question for the specific air purifier on this thread... are "Auto" and any of the labeled "1" through "5" mutually exclusive?
    - If yes, then Home Assistant would consider `auto` to be a `preset mode` and would consider `1` through `5` to be speeds mapped to the percentage slider.
    - If no, then Home Assistant would actually consider *none* of these to be a `preset mode`, and instead would want to see this as a `switch` plus a `fan` with only speed / percentage options.

This is elaborated on & confirmed in the MQTT discovery interface in the `fan.mqtt` integration docs: https://www.home-assistant.io/integrations/fan.mqtt/#payload_reset_percentage

In particular you can read the `percentage` and `preset` related parameters there to see how they interact. The MQTT interface is trying to allow flexibility in the MQTT message payloads here, while still achieving the goal of separating speed (`percentage`) from preset mode.

BUT... all of that is just how Home Assistant is choosing to model fans, based on their architectural abstraction. Fair enough if Domoticz wants to model fans in a different way!

From looking at the Domoticz code, I'm not familiar enough with the details of the data model to understand exactly how `handle_auto_discovery_fan` is reasoning about the speeds vs modes, but I do see some handling for both types of controls (a dimmer plus a selector): https://github.com/domoticz/domoticz/blob/development/hardware/MQTTAutoDiscover.cpp#L2541

Perhaps this code can be updated to mirror the Home Assistant model, as it is parsing the auto discovery protocol defined by the Home Assistant folks? Otherwise I would personally probably put any "remapping"/device-specific logic into the Domoticz discovery handler there, to customize it for that product rather than breaking the intended interface of the HA auto discovery protocol by publishing the speeds as present modes from Z2M in general. (e.g. if Domoticz wants to show "1" through "5" for this specific fan model as drop-down presets instead of using the "dimmer" style support there, I would add those additional "presets" as a hardware-specific override in the Domoticz handler, if I've understood all the moving parts correctly across the projects & hardware here 😄)

**Comment by sjorge** [comment]
For the STARKVIND you can't set auto and a fixed speed at the same time.

Setting auto will make the device automatically pick a speed. It also reports the speed it's using in the fan_speed payload.

**Comment by gizmocuz** [comment]
@cmccambridge , @sjorge , Thank you very much for your explanation. 
I will implement it using the fan speed / percentage_command_template 

Still... personally, a preset_mode of one value does not seem correct...
For this specific device, with 6 modes (auto, 1, 2, 3, 4, 5) it was better to have implementation like a climate device that only uses the preset_modes
Also much easier for the end-user to select the mode. Now (in HASS) it has to either set the mode (auto) or use the slider or set it to auto again

I can imagine there are fan's (like for a ITHO or custom device) that can set the speed from 0-100 (or 0 - 10) .. then it would make sense to use a slide of course

I wonder what would happen if all the below was removed for this device and the preset_mode was filled in with all 6 possible combinations

```
"percentage_command_template": "{{ {0:'off', 1:'1', 2:'2', 3:'3', 4:'4', 5:'5', 6:'6', 7:'7', 8:'8', 9:'9'}[value] | default('') }}",
"percentage_command_topic": "zigbee2mqtt/AirPurifier/set/fan_mode",
"percentage_state_topic": "zigbee2mqtt/AirPurifier",
"percentage_value_template": "{{ {'off':0, '1':1, '2':2, '3':3, '4':4, '5':5, '6':6, '7':7, '8':8, '9':9}[value_json.fan_mode] | default('None') }}",
"speed_range_max": 9,
"speed_range_min": 1,
"state_topic": "zigbee2mqtt/AirPurifier",
"state_value_template": "{{ value_json.fan_state }}",
```

Would it just display a dropdown for the modes?

I like the way the web interface of Zigbee2MQTT is displaying the option to select the correct state

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/2265299/0a7f9cf2-ab33-4caa-bed3-285e41a8bb81)

Thanks all for all the feedback! I will try to find a way to combine the preset mode and the percentage
I can imagine that there are other fan devices that have one mode and percentages and will check how to handle those when I find or receive a config object for this 😊
