### ISSUE TITLE
Inovelli Fan Switch (VZM35-SN): incorrect/confusing parameter definitions

### ISSUE THREAD

**Issue by rsyring** [Koenkk/zigbee-herdsman-converters#6799]
Notes and suggestions regarding the Inovelli Blue Series switches:

* [Param 258 - outputMode](https://github.com/Koenkk/zigbee-herdsman-converters/blob/6f1db13914d74eba5eb034a950b232d4ca2b2809/src/devices/inovelli.ts#L513)
  *  Both the [fan docs](https://help.inovelli.com/en/articles/8231399-blue-series-fan-switch-parameters#h_dbd1e0396d) and the [light docs](https://help.inovelli.com/en/articles/8189241-blue-series-2-1-switch-parameters#h_54bbb47fe1)  describe this as "Switch Mode" not "Output Mode".  Rename the param to match the docs?
  * The definition used in the source code "Use device as a Dimmer or an On/Off switch." is only applicable to the light.  For the fan, this parameter controls:
         Range: 0-1
         0  = Ceiling Fan (3-Speed)
         1 = Exhaust Fan (On/Off)
         Default: 1
* [Param 52 - smartBulbMode](https://github.com/Koenkk/zigbee-herdsman-converters/blob/6f1db13914d74eba5eb034a950b232d4ca2b2809/src/devices/inovelli.ts#L394C5-L394C18)
  * Naming this "smartBulbMode" when the Inovelli docs refer to it as "Smart Fan Mode" is confusing.  If the parameter has to be the same name between the two devices, then just "smartMode" for that parameter seems better.
  * Calling [value 1 - "Remote Control Mode"](https://github.com/Koenkk/zigbee-herdsman-converters/blob/6f1db13914d74eba5eb034a950b232d4ca2b2809/src/devices/inovelli.ts#L839) is inconsistent with the Inovelli docs and also what I'd expect based on the light definition.  I think "Smart Fan Mode" would be better.
*  "Brightness" in the light definition is [converted to "mode" for the fan](https://github.com/Koenkk/zigbee-herdsman-converters/blob/6f1db13914d74eba5eb034a950b232d4ca2b2809/src/devices/inovelli.ts#L80).  
  * I think "mode" is a confusing term given its already being used for both of the two params above.  I think this should be "Speed" for the fan.  
  * Additionally, it would be helpful to describe how the "on" value applies here and how its different from "high."
  * Also add a note to describe how the Speed setting interacts with `smartBulbMode`.  Is setting smartBulbMode equivalent to setting the speed to "on"?

Thanks for your consideration.

**Comment by Koenkk** [comment]
@InovelliUSA could you check this?

**Comment by InovelliUSA** [comment]
@rsyring I have made some of the suggestions. Changing the attribute names requires some additional consideration, so I chose not to do that part. You can see the changes here: https://github.com/Koenkk/zigbee-herdsman-converters/pull/7381

**Comment by Sawtaytoes** [comment]
For someone who finds this in the future, I have both `smart_bulb_mode` and `smart_fan_mode` showing up. Not sure why the latter would exist, but I guess you could use the Inovelli unit to control the lights and not the fan. Maybe?

![Image](https://github.com/user-attachments/assets/22115990-3d07-4add-a228-61b6aec21520)

![Image](https://github.com/user-attachments/assets/944b800a-af62-4a22-abb6-2f9f2bc034f5)

On the other hand, if I wanna turn off the dimmer for the lights, it has `output_mode`, but it's a boolean. Not very clear:

![Image](https://github.com/user-attachments/assets/950380b5-d80b-4a98-9598-746907467b30)

I found this thread because I noticed one of my fans with the exact same smart lights and the exact same (to my eyes) config and module and brand of fan (they even look similar) is having the lights not set correctly. They get bright enough, but not after I've re-sent the command.

Which means maybe they were stuck in dimmer-mode (which breaks smart lights), but then I found some other things which may be causing similar issues.
