### ISSUE TITLE
Bosch BTH-RA: Proposed reversion of removal of "auto mode" (as done in #6761 - 1.35.1) 

### ISSUE THREAD

**Issue by dierochade** [Koenkk/zigbee-herdsman-converters#6995]
With this merged [pull request 6761](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6761) the bosch thermostat no longer provides the system modes 'heat', 'off', and 'auto' but only 'heat' and 'off'. This was done because the device internal schedule cannot be adjusted or even deleted with z2m (at the moment). 

I would like to suggest to overthink this decision and propose to go back to all three modes.

- The device does provide this mode, so it would be the normal decision to expose it too
- It even has a hardware button/dial to select the auto mode
- If the device is in auto mode, it is reported as unknown in home assistant, what is kind of misleading
- this is a hard breaking change, if all modes have been used in the past (like I do). It thus gives less functionality, e.g.: If the changes of the schedule in auto mode are just catched and reverted by an automation, you were able to have an normal auto mode and the possibility to switch in manual mode directly at the device.

**Comment by dierochade** [comment]
@DerDreschner 
As you have been effectively provided all the code and made this work for us (Thank you very much!!), I would like to I'd like to ask you about your opinion on this.

**Comment by danielpetrovic** [comment]
It seems to be an error in the config topic provided by Zigbee2MQTT, I have the Bosch BTH-RM which had the same switch and every reboot of HA I get this log now:

`Error 'expected SwitchDeviceClass or one of 'outlet', 'switch' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/switch/0x001e5e0902910e5b/switch_window_open/config', message: '{'availability': [{'topic': 'zigbee2mqtt/bridge/state', 'value_template': '{{ value_json.state }}'}], 'command_topic': 'zigbee2mqtt/Woonkamer Thermostaat/set/window_open', 'device': {'identifiers': ['zigbee2mqtt_0x001e5e0902910e5b'], 'manufacturer': 'Bosch', 'model': 'Room thermostat II (Battery model) (BTH-RM)', 'name': 'Woonkamer Thermostaat', 'via_device': 'zigbee2mqtt_bridge_0x00124b0030eb5c72'}, 'device_class': 'window', 'object_id': 'woonkamer_thermostaat_window_open', 'origin': {'name': 'Zigbee2MQTT', 'sw_version': '1.35.2-dev', 'support_url': 'https://www.zigbee2mqtt.io'}, 'payload_off': 'OFF', 'payload_on': 'ON', 'state_topic': 'zigbee2mqtt/Woonkamer Thermostaat', 'unique_id': '0x001e5e0902910e5b_switch_window_open_zigbee2mqtt', 'value_template': '{{ value_json.window_open }}', 'platform': 'mqtt'}'
Error 'expected SwitchDeviceClass or one of 'outlet', 'switch' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/switch/0x001e5e09029103c1/switch_window_open/config', message: '{'availability': [{'topic': 'zigbee2mqtt/bridge/state', 'value_template': '{{ value_json.state }}'}], 'command_topic': 'zigbee2mqtt/Badkamer Thermostaat/set/window_open', 'device': {'identifiers': ['zigbee2mqtt_0x001e5e09029103c1'], 'manufacturer': 'Bosch', 'model': 'Room thermostat II (Battery model) (BTH-RM)', 'name': 'Badkamer Thermostaat', 'via_device': 'zigbee2mqtt_bridge_0x00124b0030eb5c72'}, 'device_class': 'window', 'object_id': 'badkamer_thermostaat_window_open', 'origin': {'name': 'Zigbee2MQTT', 'sw_version': '1.35.2-dev', 'support_url': 'https://www.zigbee2mqtt.io'}, 'payload_off': 'OFF', 'payload_on': 'ON', 'state_topic': 'zigbee2mqtt/Badkamer Thermostaat', 'unique_id': '0x001e5e09029103c1_switch_window_open_zigbee2mqtt', 'value_template': '{{ value_json.window_open }}', 'platform': 'mqtt'}'
Error 'expected SwitchDeviceClass or one of 'outlet', 'switch' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/switch/0x001e5e090290f15d/switch_window_open/config', message: '{'availability': [{'topic': 'zigbee2mqtt/bridge/state', 'value_template': '{{ value_json.state }}'}], 'command_topic': 'zigbee2mqtt/Gameroom Thermostaat/set/window_open', 'device': {'identifiers': ['zigbee2mqtt_0x001e5e090290f15d'], 'manufacturer': 'Bosch', 'model': 'Room thermostat II (Battery model) (BTH-RM)', 'name': 'Gameroom Thermostaat', 'via_device': 'zigbee2mqtt_bridge_0x00124b0030eb5c72'}, 'device_class': 'window', 'object_id': 'gameroom_thermostaat_window_open', 'origin': {'name': 'Zigbee2MQTT', 'sw_version': '1.35.2-dev', 'support_url': 'https://www.zigbee2mqtt.io'}, 'payload_off': 'OFF', 'payload_on': 'ON', 'state_topic': 'zigbee2mqtt/Gameroom Thermostaat', 'unique_id': '0x001e5e090290f15d_switch_window_open_zigbee2mqtt', 'value_template': '{{ value_json.window_open }}', 'platform': 'mqtt'}'
Error 'expected SwitchDeviceClass or one of 'outlet', 'switch' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/switch/0x001e5e090290f1cb/switch_window_open/config', message: '{'availability': [{'topic': 'zigbee2mqtt/bridge/state', 'value_template': '{{ value_json.state }}'}], 'command_topic': 'zigbee2mqtt/Kantoor Thermostaat/set/window_open', 'device': {'identifiers': ['zigbee2mqtt_0x001e5e090290f1cb'], 'manufacturer': 'Bosch', 'model': 'Room thermostat II (Battery model) (BTH-RM)', 'name': 'Kantoor Thermostaat', 'via_device': 'zigbee2mqtt_bridge_0x00124b0030eb5c72'}, 'device_class': 'window', 'object_id': 'kantoor_thermostaat_window_open', 'origin': {'name': 'Zigbee2MQTT', 'sw_version': '1.35.2-dev', 'support_url': 'https://www.zigbee2mqtt.io'}, 'payload_off': 'OFF', 'payload_on': 'ON', 'state_topic': 'zigbee2mqtt/Kantoor Thermostaat', 'unique_id': '0x001e5e090290f1cb_switch_window_open_zigbee2mqtt', 'value_template': '{{ value_json.window_open }}', 'platform': 'mqtt'}'
Error 'expected SwitchDeviceClass or one of 'outlet', 'switch' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/switch/0x001e5e090290e78d/switch_window_open/config', message: '{'availability': [{'topic': 'zigbee2mqtt/bridge/state', 'value_template': '{{ value_json.state }}'}], 'command_topic': 'zigbee2mqtt/Sauna Thermostaat/set/window_open', 'device': {'identifiers': ['zigbee2mqtt_0x001e5e090290e78d'], 'manufacturer': 'Bosch', 'model': 'Room thermostat II (Battery model) (BTH-RM)', 'name': 'Sauna Thermostaat', 'via_device': 'zigbee2mqtt_bridge_0x00124b0030eb5c72'}, 'device_class': 'window', 'object_id': 'sauna_thermostaat_window_open', 'origin': {'name': 'Zigbee2MQTT', 'sw_version': '1.35.2-dev', 'support_url': 'https://www.zigbee2mqtt.io'}, 'payload_off': 'OFF', 'payload_on': 'ON', 'state_topic': 'zigbee2mqtt/Sauna Thermostaat', 'unique_id': '0x001e5e090290e78d_switch_window_open_zigbee2mqtt', 'value_template': '{{ value_json.window_open }}', 'platform': 'mqtt'}' `

The switch has since disappeared from HA.
