### ISSUE TITLE
Reduce frequency of energy reporting

### ISSUE THREAD

**Issue by djchen** [Koenkk/zigbee-herdsman-converters#940]
My 45853GE and Securifi Peanut smart plugs report their energy related attributes much more frequently than I'd like it to and I believe much more frequently than they need to. The side effect is that this makes my Home Assistant database much larger since the values are coming in almost every second or every other second.

@Koenkk Do you think it's ok to raise the `minimumReportInterval` to something like 30 seconds or can we make this interval configurable option per device?
https://github.com/Koenkk/zigbee-herdsman-converters/blob/8af36f039ef4a3976e825fae4709fb35faef2fcf/devices.js#L125

Just want to get your thoughts here. I'm happy to submit a PR if the right approach is found.

Thanks!

**Comment by Koenkk** [comment]
Change the min report interval to 5 and reportablechange to 10 or 100 (so that it will only send values once there is a significant change)

**Comment by djchen** [comment]
> Change the min report interval to 5 and reportablechange to 10 or 100 (so that it will only send values once there is a significant change)

Assuming that works though, we wouldn't necessarily want to commit that change for all devices?

**Comment by Koenkk** [comment]
No, but we can easily specify different values for this device through parameters.

**Comment by airdrummingfool** [comment]
I've been thinking about this recently also. I have a few energy-reporting smart plugs that I use to determine if a device is on or off (based on power draw). A 5 second delay in status updates is fine, but having to wait 30 seconds to know that a device changed state is too long in my opinion.

On the flip side, I also have a few smart plugs that report energy usage that I totally ignore. It would be awesome to be able to configure each device separately, but short of that, it's probably worth setting different `reportableChange` values for each device. E.g. I have some Iris `3210-L` plugs that report current in milliamps. A change as small as 0.001 amps triggers a new message from the sensor, but the difference is so small it doesn't even change the value reported via MQTT (which only reports down to 0.01 amps).

A thought: instead of having to provide all parameters when we want to provide custom values to `endpoint.configureReporting()`, what if the `configureReporting` convenience methods accepted an optional second object parameter that was merged with the existing parameters, so we could e.g. override only `reportableChange`?

modified `configureReporting.rmsCurrent()`:
```
    rmsCurrent: async (endpoint, overrides) => {
        const payload = [{
            attribute: 'rmsCurrent',
            minimumReportInterval: 5,
            maximumReportInterval: repInterval.MINUTES_5,
            reportableChange: 1,
        }];
        Object.assign(payload[0], overrides); // merge overrides into the payload
        await endpoint.configureReporting('haElectricalMeasurement', payload);
    },
```

with the `Object.assign` call in the convenience method, in order to override `reportableChange` from the `configure` method, I could just do:
```
await configureReporting.rmsCurrent(endpoint, {'reportableChange': 100});
```

without the `Object.assign` call, I would have to do the following:
```
const payload = {
    attribute: 'rmsCurrent',
    minimumReportInterval: 5,
    maximumReportInterval: repInterval.MINUTES_5,
    reportableChange: 100,
}
await endpoint.configureReporting('haElectricalMeasurement', payload);
```

**Comment by Koenkk** [comment]
@airdrummingfool `Object.assign` looks like a good idea too me, great :smile:
